[package]
authors = ["Leéh Péter <leeh123peter@gmail.com>"]
name = "pysprint"
version = "0.1.0"
edition = "2018"

[dependencies.pyo3]
version = "0.14.2"
features = ["extension-module"]

[dependencies]
ctrlc = "3.1"

[lib]
name = "pysprint"
crate-type = ["cdylib"]