name: pysprint-dev
channels:
  - conda-forge
  - anaconda
dependencies:
  # required and optional
  - python=3.8
  - numpy>=1.15
  - matplotlib
  - pandas
  - scipy
  - numba
  - lmfit
  - Jinja2
  - dask

  # dev
  - setuptools-rust
  - setuptools
  - wheel
  - pip

  # docs
  - sphinx
  - nbsphinx
  - recommonmark
  - sphinx_rtd_theme
  - nbconvert

  # Strictly speaking this is not neseccary, but better safe than sorry
  - ipython
  - jupyter
  - ipykernel
  - ipywidgets
  - nbformat
  - notebook


  # code checks
  - black
  - flake8
  - pytest
  - codecov
  - coverage
  - tox
